### ISSUE TITLE
Hide your secrets

### ISSUE THREAD

**Issue by akankov** [OjasMittal/WeatherCalorieCalculator#2]
Hi!

🚨 You should never expose your API keys and other sensitive parameters of your app in the course code

**Comment by OjasMittal** [comment]
Thanks for informing @akankov, had forgotten totally about firebase API KEY, hidden it now

**Comment by akankov** [comment]
Did you?
I still can see it in [this](https://github.com/OjasMittal/WeatherCalorieCalculator/commit/80c01df338743b956d542eaf156a12a4ed28a048) commit 😉

**Comment by OjasMittal** [comment]
oh, it's in the previous commits, I have no clue how to hide them, I will try browsing it.....Thanks again.....
